language: c
sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode8

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

matrix:
  allow_failures:
    - os: osx
  exclude:
    - os: osx
      compiler: gcc
  fast_finish: true

cache:
  apt: true
  directories:
    - $HOME/.whatever

script:
  - mkdir build
  - cd build
  - cmake -DUCDN_CFLAGS="--coverage" -DBUILD_ALLOW_SHLIB_UNDEFINED=ON -DCMAKE_BUILD_TYPE=Release -DWHATEVER_CACHE_DIR="${HOME}/.whatever" ..
  - make && make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

