language: c
sudo: false

compiler:
  - gcc
  - clang

os: linux

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

matrix:
  allow_failures:
    - compiler: clang
  fast_finish: true

cache:
  apt: true

script:
  - mkdir build
  - cd build
  - cmake --DCMAKE_BUILD_TYPE=Release ..
  - make

