version: 1.0.0.{build}-{branch}
image: Visual Studio 2015

pull_requests:
  do_not_increment_build_number: true

install:
  - git submodule update --init --recursive

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - mkdir build32
  - mkdir build64
  - mkdir output32
  - mkdir output64
  - cd build32
  - cmake -G "Visual Studio 14 2015" ..
  - msbuild PACKAGE.vcxproj /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd ../build64
  - cmake -G "Visual Studio 14 2015" -DCMAKE_GENERATOR_PLATFORM="x64" ..
  - msbuild PACKAGE.vcxproj /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd ..

after_build:
  - ps: Get-ChildItem .\build32\ucdn*.7z | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\build64\ucdn*.7z | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

