version: 1.0.0.{build}-{branch}
image: Visual Studio 2015

pull_requests:
  do_not_increment_build_number: true

install:
  - git submodule update --init --recursive

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - mkdir build32
  - mkdir build64
  - mkdir output32
  - mkdir output64
  - cd build32
  - cmake -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\output32" ..
  - msbuild INSTALL.vcxproj /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd ../build64
  - cmake -G "Visual Studio 14 2015" -DCMAKE_GENERATOR_PLATFORM="x64" -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\output64" ..
  - msbuild INSTALL.vcxproj /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: .\output32\
    name: ucdn_we-vc14-x86
  - path: .\output64\
    name: ucdn_we-vc14-x86_64

